head_controller:
  type: position_controllers/JointTrajectoryController
  topic: "test"
  joints:
     - neck_tilt
     - neckpan
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.5
      neck_tilt: {trajectory: 0.1, goal: 0.1}
      neckpan: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
